### ISSUE TITLE
Documentation "Templates" are unavailable 

### ISSUE THREAD

**Issue by JPVenson** [dotnet-dash/dash#40]
It seems like both links from readthedocs are not available:
Templates
- Built-in Templates
- Custom Templates

https://dotnet-dash.readthedocs.io/en/latest/templates/built-in-templates.md
https://dotnet-dash.readthedocs.io/en/latest/templates/custom-templates.md

**Comment by hhoangnl** [comment]
Thanks. Will update documentation
